### ISSUE TITLE
Datapicker conflicting with ACF's jQuery UI datepicker

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/events#2]
Background and previous / next month buttons are missing.

![screen shot 2016-04-29 at 12 54 06](https://cloud.githubusercontent.com/assets/786875/14914360/982c5352-0e09-11e6-86d9-6a13e19c1762.png)

**Comment by sboerrigter** [comment]
Apparently this is a conflict with ACF's jQuery UI datepicker script

**Comment by haroldangenent** [comment]
Suggesting to close this in favor of #3 (at some point).

**Comment by sboerrigter** [comment]
Ok
